"""add subscriptions

Revision ID: 1060ec53e225
Revises: 147fa116dfea
Create Date: 2026-09-01 16:59:00.304426

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1060ec53e225"
down_revision: str | Sequence[str] | None = "147fa116dfea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_subscription_endpoint_event_type", "subscriptions", ["endpoint_id", "event_type"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_subscription_endpoint_event_type", "subscriptions", type_="unique")
    # ### end Alembic commands ###
