"""add subscriptions

Revision ID: 147fa116dfea
Revises: 683ded13c461
Create Date: 2026-09-01 10:41:38.883712

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "147fa116dfea"
down_revision: str | Sequence[str] | None = "683ded13c461"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("endpoint_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["endpoint_id"],
            ["endpoints.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscriptions_endpoint_id"), "subscriptions", ["endpoint_id"], unique=False
    )
    op.create_index(
        op.f("ix_subscriptions_event_type"), "subscriptions", ["event_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscriptions_event_type"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_endpoint_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    # ### end Alembic commands ###
